#! /bin/sh

set -eu

awkprog='
  {
    prev_line = line
    line = $0
    sum = $1
    if (sum == prev_sum) {
      num_matches++
    } else {
      num_matches = 0
    }
    if (num_matches > 0) {
      if (num_matches == 1) {
        printf("Duplicates:\n\t%s\n", prevline)
      }
      printf("\t%s\n", line)
    }
    prev_sum = sum
  }
'

find "$@" -type f -print0 \
  | xargs -0 shasum -b -a 256 \
  | sort \
  | awk "$awkprog" \

